//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EthozCapital.AlertListWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlertListWSSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseEntitiesComponents))]
    public partial class AlertListWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetClientCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCusAlertListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateWaiveDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientAlertReasonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlertListWS() {
            this.Url = global::EthozCapital.Properties.Settings.Default.EthozCapital_AlertListWS_AlertListWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetClientCodeCompletedEventHandler GetClientCodeCompleted;
        
        /// <remarks/>
        public event CheckCusAlertListCompletedEventHandler CheckCusAlertListCompleted;
        
        /// <remarks/>
        public event UpdateWaiveDetailCompletedEventHandler UpdateWaiveDetailCompleted;
        
        /// <remarks/>
        public event GetConnectionStringCompletedEventHandler GetConnectionStringCompleted;
        
        /// <remarks/>
        public event GetClientAlertReasonCompletedEventHandler GetClientAlertReasonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetClientCode(string AS_Connection, string LS_CusType, string LS_CusCode) {
            object[] results = this.Invoke("GetClientCode", new object[] {
                        AS_Connection,
                        LS_CusType,
                        LS_CusCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientCodeAsync(string AS_Connection, string LS_CusType, string LS_CusCode) {
            this.GetClientCodeAsync(AS_Connection, LS_CusType, LS_CusCode, null);
        }
        
        /// <remarks/>
        public void GetClientCodeAsync(string AS_Connection, string LS_CusType, string LS_CusCode, object userState) {
            if ((this.GetClientCodeOperationCompleted == null)) {
                this.GetClientCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientCodeOperationCompleted);
            }
            this.InvokeAsync("GetClientCode", new object[] {
                        AS_Connection,
                        LS_CusType,
                        LS_CusCode}, this.GetClientCodeOperationCompleted, userState);
        }
        
        private void OnGetClientCodeOperationCompleted(object arg) {
            if ((this.GetClientCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientCodeCompleted(this, new GetClientCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckCusAlertList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckCusAlertList(string AS_Connection, entAlertUtil AlertParameter) {
            object[] results = this.Invoke("CheckCusAlertList", new object[] {
                        AS_Connection,
                        AlertParameter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCusAlertListAsync(string AS_Connection, entAlertUtil AlertParameter) {
            this.CheckCusAlertListAsync(AS_Connection, AlertParameter, null);
        }
        
        /// <remarks/>
        public void CheckCusAlertListAsync(string AS_Connection, entAlertUtil AlertParameter, object userState) {
            if ((this.CheckCusAlertListOperationCompleted == null)) {
                this.CheckCusAlertListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCusAlertListOperationCompleted);
            }
            this.InvokeAsync("CheckCusAlertList", new object[] {
                        AS_Connection,
                        AlertParameter}, this.CheckCusAlertListOperationCompleted, userState);
        }
        
        private void OnCheckCusAlertListOperationCompleted(object arg) {
            if ((this.CheckCusAlertListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCusAlertListCompleted(this, new CheckCusAlertListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateWaiveDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateWaiveDetail(string AS_Connection, entAlertUtil AlertParameter) {
            object[] results = this.Invoke("UpdateWaiveDetail", new object[] {
                        AS_Connection,
                        AlertParameter});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateWaiveDetailAsync(string AS_Connection, entAlertUtil AlertParameter) {
            this.UpdateWaiveDetailAsync(AS_Connection, AlertParameter, null);
        }
        
        /// <remarks/>
        public void UpdateWaiveDetailAsync(string AS_Connection, entAlertUtil AlertParameter, object userState) {
            if ((this.UpdateWaiveDetailOperationCompleted == null)) {
                this.UpdateWaiveDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateWaiveDetailOperationCompleted);
            }
            this.InvokeAsync("UpdateWaiveDetail", new object[] {
                        AS_Connection,
                        AlertParameter}, this.UpdateWaiveDetailOperationCompleted, userState);
        }
        
        private void OnUpdateWaiveDetailOperationCompleted(object arg) {
            if ((this.UpdateWaiveDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateWaiveDetailCompleted(this, new UpdateWaiveDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConnectionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetConnectionString(string LS_UserID, string LS_Password, string LS_Server, string LS_DatabaseName) {
            object[] results = this.Invoke("GetConnectionString", new object[] {
                        LS_UserID,
                        LS_Password,
                        LS_Server,
                        LS_DatabaseName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetConnectionStringAsync(string LS_UserID, string LS_Password, string LS_Server, string LS_DatabaseName) {
            this.GetConnectionStringAsync(LS_UserID, LS_Password, LS_Server, LS_DatabaseName, null);
        }
        
        /// <remarks/>
        public void GetConnectionStringAsync(string LS_UserID, string LS_Password, string LS_Server, string LS_DatabaseName, object userState) {
            if ((this.GetConnectionStringOperationCompleted == null)) {
                this.GetConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetConnectionString", new object[] {
                        LS_UserID,
                        LS_Password,
                        LS_Server,
                        LS_DatabaseName}, this.GetConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetConnectionStringOperationCompleted(object arg) {
            if ((this.GetConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConnectionStringCompleted(this, new GetConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientAlertReason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetClientAlertReason(string AS_Connection, entAlertUtil AlertParameter) {
            object[] results = this.Invoke("GetClientAlertReason", new object[] {
                        AS_Connection,
                        AlertParameter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientAlertReasonAsync(string AS_Connection, entAlertUtil AlertParameter) {
            this.GetClientAlertReasonAsync(AS_Connection, AlertParameter, null);
        }
        
        /// <remarks/>
        public void GetClientAlertReasonAsync(string AS_Connection, entAlertUtil AlertParameter, object userState) {
            if ((this.GetClientAlertReasonOperationCompleted == null)) {
                this.GetClientAlertReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientAlertReasonOperationCompleted);
            }
            this.InvokeAsync("GetClientAlertReason", new object[] {
                        AS_Connection,
                        AlertParameter}, this.GetClientAlertReasonOperationCompleted, userState);
        }
        
        private void OnGetClientAlertReasonOperationCompleted(object arg) {
            if ((this.GetClientAlertReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientAlertReasonCompleted(this, new GetClientAlertReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class entAlertUtil : baseEntitiesComponents {
        
        private string transCodeField;
        
        private string claimTypeField;
        
        private string parameter1Field;
        
        private string parameter2Field;
        
        private string parameter3Field;
        
        private string parameter4Field;
        
        private string parameter5Field;
        
        /// <remarks/>
        public string TransCode {
            get {
                return this.transCodeField;
            }
            set {
                this.transCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimType {
            get {
                return this.claimTypeField;
            }
            set {
                this.claimTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Parameter1 {
            get {
                return this.parameter1Field;
            }
            set {
                this.parameter1Field = value;
            }
        }
        
        /// <remarks/>
        public string Parameter2 {
            get {
                return this.parameter2Field;
            }
            set {
                this.parameter2Field = value;
            }
        }
        
        /// <remarks/>
        public string Parameter3 {
            get {
                return this.parameter3Field;
            }
            set {
                this.parameter3Field = value;
            }
        }
        
        /// <remarks/>
        public string Parameter4 {
            get {
                return this.parameter4Field;
            }
            set {
                this.parameter4Field = value;
            }
        }
        
        /// <remarks/>
        public string Parameter5 {
            get {
                return this.parameter5Field;
            }
            set {
                this.parameter5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(entAlertUtil))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class baseEntitiesComponents {
        
        private string employeeCodeField;
        
        private string userCodeField;
        
        private string userNameField;
        
        private string clientCodeField;
        
        private string clientNameField;
        
        private string countryCodeField;
        
        private string companyCodeField;
        
        private string iDTypeField;
        
        private string entityTypeField;
        
        private string placeIncorporationField;
        
        private System.DateTime appointmentDateField;
        
        private string designationGroupCodeField;
        
        private string nationalityField;
        
        private string currencyCodeField;
        
        private string createdByField;
        
        private System.DateTime createdDateField;
        
        private string statusIndicatorField;
        
        private string staffWhoField;
        
        private System.DateTime staDateField;
        
        private string addressCodeField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private System.DateTime effectiveDateField;
        
        private System.DateTime renewalDateField;
        
        private System.DateTime expiryDateField;
        
        private System.DateTime annualDeclarationDateField;
        
        private string tableNameField;
        
        private string textFieldField;
        
        private string valueFieldField;
        
        private string criteriaField;
        
        private string sortByField;
        
        private string customerCodeField;
        
        private string customerTypeField;
        
        private string requestNumberField;
        
        private System.DateTime requestDateField;
        
        private int itemNumberField;
        
        private int subItemNumberField;
        
        private string errorStatusField;
        
        private string errorDescriptionField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string buildingNameField;
        
        private string postalCodeField;
        
        private string addressSourceField;
        
        private string phoneNumberField;
        
        private string webAddressField;
        
        /// <remarks/>
        public string EmployeeCode {
            get {
                return this.employeeCodeField;
            }
            set {
                this.employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCode {
            get {
                return this.clientCodeField;
            }
            set {
                this.clientCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceIncorporation {
            get {
                return this.placeIncorporationField;
            }
            set {
                this.placeIncorporationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AppointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                this.appointmentDateField = value;
            }
        }
        
        /// <remarks/>
        public string DesignationGroupCode {
            get {
                return this.designationGroupCodeField;
            }
            set {
                this.designationGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public string StatusIndicator {
            get {
                return this.statusIndicatorField;
            }
            set {
                this.statusIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string StaffWho {
            get {
                return this.staffWhoField;
            }
            set {
                this.staffWhoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StaDate {
            get {
                return this.staDateField;
            }
            set {
                this.staDateField = value;
            }
        }
        
        /// <remarks/>
        public string AddressCode {
            get {
                return this.addressCodeField;
            }
            set {
                this.addressCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RenewalDate {
            get {
                return this.renewalDateField;
            }
            set {
                this.renewalDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AnnualDeclarationDate {
            get {
                return this.annualDeclarationDateField;
            }
            set {
                this.annualDeclarationDateField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public string TextField {
            get {
                return this.textFieldField;
            }
            set {
                this.textFieldField = value;
            }
        }
        
        /// <remarks/>
        public string ValueField {
            get {
                return this.valueFieldField;
            }
            set {
                this.valueFieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
        
        /// <remarks/>
        public string SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestNumber {
            get {
                return this.requestNumberField;
            }
            set {
                this.requestNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public int ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public int SubItemNumber {
            get {
                return this.subItemNumberField;
            }
            set {
                this.subItemNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorStatus {
            get {
                return this.errorStatusField;
            }
            set {
                this.errorStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AddressSource {
            get {
                return this.addressSourceField;
            }
            set {
                this.addressSourceField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WebAddress {
            get {
                return this.webAddressField;
            }
            set {
                this.webAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetClientCodeCompletedEventHandler(object sender, GetClientCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CheckCusAlertListCompletedEventHandler(object sender, CheckCusAlertListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCusAlertListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCusAlertListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateWaiveDetailCompletedEventHandler(object sender, UpdateWaiveDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateWaiveDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateWaiveDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetConnectionStringCompletedEventHandler(object sender, GetConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetClientAlertReasonCompletedEventHandler(object sender, GetClientAlertReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientAlertReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientAlertReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591