//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_att_access
    {
        public string aa_emp_cod { get; set; }
        public string aa_main_dept { get; set; }
        public string aa_sub_dept { get; set; }
        public string aa_att_emp { get; set; }
        public string aa_sta_ind { get; set; }
        public string aa_sta_who { get; set; }
        public Nullable<System.DateTime> aa_sta_dat { get; set; }
        public string aa_att_loc { get; set; }
    }
}
