//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_app_officer
    {
        public string ao_emp_cod { get; set; }
        public string ao_cat_cod { get; set; }
        public string ao_pri_cod { get; set; }
        public string ao_sec_cod { get; set; }
        public string ao_sta_ind { get; set; }
        public string ao_sta_who { get; set; }
        public Nullable<System.DateTime> ao_sta_dat { get; set; }
    }
}
