//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_att_det
    {
        public int ad_rec_num { get; set; }
        public string ad_ter_num { get; set; }
        public string ad_thm_num { get; set; }
        public string ad_emp_cod { get; set; }
        public System.DateTime ad_att_dat { get; set; }
        public string ad_sta_ind { get; set; }
        public string ad_sta_who { get; set; }
        public Nullable<System.DateTime> ad_sta_dat { get; set; }
    }
}
