//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_att_rem_ark2
    {
        public int ar_rec_num { get; set; }
        public string ar_emp_cod { get; set; }
        public System.DateTime ar_att_dat { get; set; }
        public string ar_sta_tus { get; set; }
        public string ar_rem_ark { get; set; }
        public string ar_sta_ind { get; set; }
        public string ar_sta_who { get; set; }
        public Nullable<System.DateTime> ar_sta_dat { get; set; }
        public string ar_rem_ind { get; set; }
    }
}
