//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_att_deduct
    {
        public int ad_ded_cod { get; set; }
        public string ad_abs_bat_num { get; set; }
        public Nullable<int> ad_abs_itm_num { get; set; }
        public string ad_lev_bat_num { get; set; }
        public Nullable<int> ad_lev_itm_num { get; set; }
        public Nullable<bool> ad_ded_am { get; set; }
        public Nullable<bool> ad_ded_pm { get; set; }
        public Nullable<System.DateTime> ad_pay_dat { get; set; }
        public Nullable<bool> ad_ded_ind { get; set; }
        public Nullable<bool> ad_exp_ind { get; set; }
        public Nullable<System.DateTime> ad_exp_dat { get; set; }
        public string ad_sta_ind { get; set; }
        public string ad_sta_who { get; set; }
        public Nullable<System.DateTime> ad_sta_dat { get; set; }
        public string ad_app_sta { get; set; }
        public Nullable<System.DateTime> ad_waive_dat { get; set; }
    }
}
