//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_abs_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ss_abs_mas()
        {
            this.ss_abs_det = new HashSet<ss_abs_det>();
        }
    
        public string am_bat_num { get; set; }
        public Nullable<System.DateTime> am_bat_dat { get; set; }
        public string am_emp_cod { get; set; }
        public string am_sta_ind { get; set; }
        public string am_sta_who { get; set; }
        public Nullable<System.DateTime> am_sta_dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_abs_det> ss_abs_det { get; set; }
    }
}
