//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_att_aws
    {
        public int aa_aws_cod { get; set; }
        public string aa_emp_cod { get; set; }
        public Nullable<System.DateTime> aa_eff_dat { get; set; }
        public Nullable<decimal> aa_cap_amt { get; set; }
        public Nullable<decimal> aa_deduct_amt { get; set; }
        public string aa_sta_ind { get; set; }
        public string aa_sta_who { get; set; }
        public Nullable<System.DateTime> aa_sta_dat { get; set; }
    }
}
