//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_abs_det
    {
        public string ad_bat_num { get; set; }
        public int ad_itm_num { get; set; }
        public System.DateTime ad_lev_dat { get; set; }
        public string ad_lev_cod { get; set; }
        public bool ad_lev_am { get; set; }
        public bool ad_lev_pm { get; set; }
        public string ad_lev_typ { get; set; }
        public string ad_rem_ark { get; set; }
        public string ad_mrk_by { get; set; }
        public string ad_mrk_ind { get; set; }
        public Nullable<System.DateTime> ad_mrk_dat { get; set; }
        public string ad_mrk_who { get; set; }
        public Nullable<System.DateTime> ad_con_dat { get; set; }
        public string ad_con_who { get; set; }
        public string ad_sta_ind { get; set; }
        public string ad_sta_who { get; set; }
        public Nullable<System.DateTime> ad_sta_dat { get; set; }
        public Nullable<int> ad_mail_ind { get; set; }
    
        public virtual ss_abs_mas ss_abs_mas { get; set; }
    }
}
