//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_buddy
    {
        public string sb_emp_cod { get; set; }
        public string sb_bdy_cod { get; set; }
        public string sb_grp_cod { get; set; }
        public string sb_sta_ind { get; set; }
        public string sb_sta_who { get; set; }
        public Nullable<System.DateTime> sb_sta_dat { get; set; }
    }
}
