//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_clm_typ
    {
        public string ct_clm_cod { get; set; }
        public string ct_cat_cod { get; set; }
        public string ct_clm_desc { get; set; }
        public string ct_shr_nam { get; set; }
        public string ct_gl_cod { get; set; }
        public string ct_cri_teria { get; set; }
        public string ct_ent_typ { get; set; }
        public string ct_rem_ark { get; set; }
        public string ct_sta_ind { get; set; }
        public string ct_sta_who { get; set; }
        public Nullable<System.DateTime> ct_sta_dat { get; set; }
    }
}
