//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_clm_det
    {
        public string cd_bat_num { get; set; }
        public int cd_itm_num { get; set; }
        public System.DateTime cd_rec_dat { get; set; }
        public string cd_rec_num { get; set; }
        public string cd_typ_cod { get; set; }
        public string cd_grp_cod { get; set; }
        public string cd_veh_num { get; set; }
        public string cd_clm_cod { get; set; }
        public string cd_pay_cod { get; set; }
        public string cd_pay_to { get; set; }
        public decimal cd_rec_amt { get; set; }
        public decimal cd_clm_amt { get; set; }
        public Nullable<decimal> cd_paid_amt { get; set; }
        public string cd_rem_ark { get; set; }
        public string cd_ver_by { get; set; }
        public Nullable<System.DateTime> cd_ver_dat { get; set; }
        public string cd_ver_remark { get; set; }
        public string cd_app_by { get; set; }
        public string cd_app_ind { get; set; }
        public Nullable<System.DateTime> cd_app_dat { get; set; }
        public string cd_app_who { get; set; }
        public string cd_app_remark { get; set; }
        public string cd_pay_ind { get; set; }
        public string cd_pay_who { get; set; }
        public Nullable<System.DateTime> cd_pay_dat { get; set; }
        public string cd_ref_num { get; set; }
        public string cd_sta_ind { get; set; }
        public string cd_sta_who { get; set; }
        public Nullable<System.DateTime> cd_sta_dat { get; set; }
        public string cd_clm_ind { get; set; }
        public Nullable<System.DateTime> cd_clm_dat { get; set; }
        public string cd_pro_ind { get; set; }
        public string cd_srv_num { get; set; }
        public string cd_sup_inv_num { get; set; }
        public Nullable<decimal> cd_taxable { get; set; }
        public Nullable<decimal> cd_gst_amt { get; set; }
        public string cd_loc_cod { get; set; }
        public string cd_clm_des { get; set; }
        public string cd_directpay_ind { get; set; }
        public string cd_directpay_ref_num { get; set; }
        public string cd_directpay_who { get; set; }
        public Nullable<System.DateTime> cd_directpay_dat { get; set; }
    
        public virtual ss_clm_mas ss_clm_mas { get; set; }
    }
}
