//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_clm_emp_det
    {
        public string cd_ref_cod { get; set; }
        public string cd_clm_cod { get; set; }
        public Nullable<decimal> cd_clm_bf { get; set; }
        public Nullable<decimal> cd_clm_ent { get; set; }
        public Nullable<decimal> cd_cur_ent { get; set; }
        public Nullable<decimal> cd_clm_add { get; set; }
        public Nullable<decimal> cd_clm_tot { get; set; }
        public Nullable<decimal> cd_clm_tak { get; set; }
        public Nullable<decimal> cd_clm_bal { get; set; }
        public string cd_sys_sta { get; set; }
    
        public virtual ss_clm_emp_mas ss_clm_emp_mas { get; set; }
    }
}
