//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_ccl_param
    {
        public int cp_rec_num { get; set; }
        public System.DateTime cp_eff_dat { get; set; }
        public int cp_srv_mth { get; set; }
        public int cp_srv_ent { get; set; }
        public string cp_sta_ind { get; set; }
        public string cp_sta_who { get; set; }
        public Nullable<System.DateTime> cp_sta_dat { get; set; }
    }
}
