//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_dept_det
    {
        public string dd_grp_cod { get; set; }
        public string dd_dept_cod { get; set; }
        public string dd_tel_num { get; set; }
        public string dd_fax_num { get; set; }
        public string dd_email { get; set; }
        public string dd_old_dept_cod { get; set; }
        public string dd_sta_ind { get; set; }
        public string dd_sta_who { get; set; }
        public System.DateTime dd_sta_dat { get; set; }
    }
}
