//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_dept_chd
    {
        public string dc_grp_cod { get; set; }
        public string dc_dept_cod { get; set; }
        public string dc_dept_grp_cod { get; set; }
        public string dc_sta_ind { get; set; }
        public string dc_sta_who { get; set; }
        public System.DateTime dc_sta_dat { get; set; }
    }
}
