//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_date_release
    {
        public int dr_ref_cod { get; set; }
        public string dr_emp_cod { get; set; }
        public string dr_typ_ind { get; set; }
        public System.DateTime dr_rel_dat { get; set; }
        public string dr_sta_ind { get; set; }
        public string dr_sta_who { get; set; }
        public Nullable<System.DateTime> dr_sta_dat { get; set; }
    }
}
