//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_mas_add
    {
        public string ma_emp_cod { get; set; }
        public string ma_lev_ent_ind { get; set; }
        public string ma_lev_auto_ind { get; set; }
        public Nullable<int> ma_lev_app_days { get; set; }
        public string ma_clm_ent_ind { get; set; }
        public string ma_clm_auto_ind { get; set; }
        public Nullable<int> ma_clm_app_days { get; set; }
        public string ma_sta_ind { get; set; }
        public string ma_sta_who { get; set; }
        public Nullable<System.DateTime> ma_sta_dat { get; set; }
        public string ma_phone_ind { get; set; }
        public string ma_pc_ind { get; set; }
        public string ma_pc_sta { get; set; }
        public string ma_rem_ark { get; set; }
    
        public virtual ss_emp_mas ss_emp_mas { get; set; }
    }
}
