//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_appoint_ment
    {
        public int ea_app_num { get; set; }
        public string ea_emp_cod { get; set; }
        public System.DateTime ea_app_dat { get; set; }
        public string ea_typ_cod { get; set; }
        public string ea_rem_ark { get; set; }
        public string ea_sta_ind { get; set; }
        public string ea_sta_who { get; set; }
        public Nullable<System.DateTime> ea_sta_dat { get; set; }
    }
}
