//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_offday_det
    {
        public string od_ref_cod { get; set; }
        public int od_itm_num { get; set; }
        public System.DateTime od_off_dat { get; set; }
        public string od_sta_ind { get; set; }
        public string od_sta_who { get; set; }
        public Nullable<System.DateTime> od_sta_dat { get; set; }
    
        public virtual ss_emp_offday_mas ss_emp_offday_mas { get; set; }
    }
}
