//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_category
    {
        public string ec_cat_cod { get; set; }
        public string ec_cat_desc { get; set; }
        public Nullable<int> ec_cat_ord { get; set; }
        public string ec_sta_ind { get; set; }
        public string ec_sta_who { get; set; }
        public Nullable<System.DateTime> ec_sta_dat { get; set; }
    }
}
