//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_ecard_mails
    {
        public int ec_mail_num { get; set; }
        public string ec_mail_typ { get; set; }
        public int ec_ref_num { get; set; }
        public string ec_mail_from { get; set; }
        public string ec_mail_to { get; set; }
        public string ec_mail_sub { get; set; }
        public string ec_mail_body { get; set; }
        public string ec_sta_ind { get; set; }
        public string ec_sta_who { get; set; }
        public Nullable<System.DateTime> ec_sta_dat { get; set; }
    }
}
