//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_pic
    {
        public string ep_emp_code { get; set; }
        public string ep_pic_typ { get; set; }
        public byte[] ep_pic_byte { get; set; }
        public Nullable<System.DateTime> ep_sta_dat { get; set; }
        public string ep_sta_who { get; set; }
    }
}
