//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_mas
    {
        public string em_emp_cod { get; set; }
        public string em_title { get; set; }
        public string em_initial { get; set; }
        public string em_emp_nam { get; set; }
        public string em_alias_nam { get; set; }
        public string em_sht_nam { get; set; }
        public string em_emp_nation { get; set; }
        public string em_citizen_sta { get; set; }
        public string em_nric_type { get; set; }
        public string em_nric_no { get; set; }
        public string em_birth_place { get; set; }
        public Nullable<System.DateTime> em_birth_dat { get; set; }
        public string em_emp_gender { get; set; }
        public string em_mar_sta { get; set; }
        public string em_emp_race { get; set; }
        public string em_dialect_grp { get; set; }
        public string em_emp_religion { get; set; }
        public string em_wrk_per { get; set; }
        public string em_fin_no { get; set; }
        public Nullable<System.DateTime> em_exp_dat { get; set; }
        public Nullable<System.DateTime> em_pr_dat { get; set; }
        public string em_lic_sta { get; set; }
        public string em_lic_num { get; set; }
        public Nullable<System.DateTime> em_iss_dat { get; set; }
        public Nullable<System.DateTime> em_lic_exp_dat { get; set; }
        public Nullable<double> em_height { get; set; }
        public Nullable<double> em_weight { get; set; }
        public string em_hea_con { get; set; }
        public string em_ill_ness { get; set; }
        public string em_treat_ment { get; set; }
        public string em_ns_sta { get; set; }
        public string em_ns_voc { get; set; }
        public string em_ns_rank { get; set; }
        public string em_ns_ord { get; set; }
        public Nullable<System.DateTime> em_child_dob { get; set; }
        public string em_blk_no { get; set; }
        public string em_str_nam { get; set; }
        public string em_lvl_no { get; set; }
        public string em_unit_no { get; set; }
        public string em_build_nam { get; set; }
        public string em_zip_cod { get; set; }
        public string em_loc_home { get; set; }
        public string em_loc_mob { get; set; }
        public string em_loc_pager { get; set; }
        public string em_loc_con { get; set; }
        public string em_email { get; set; }
        public string em_con_person { get; set; }
        public string em_con_no { get; set; }
        public string em_con_mail { get; set; }
        public string em_con_relation { get; set; }
        public string em_category { get; set; }
        public Nullable<System.DateTime> em_join_dat { get; set; }
        public string em_emp_sta { get; set; }
        public Nullable<int> em_pro_period { get; set; }
        public Nullable<System.DateTime> em_cfm_dat { get; set; }
        public Nullable<System.DateTime> em_rsg_dat { get; set; }
        public string em_rsg_reason { get; set; }
        public string em_inc_tax { get; set; }
        public string em_cpf_sta { get; set; }
        public string em_emp_cpf { get; set; }
        public string em_con_sta { get; set; }
        public string em_ot_sta { get; set; }
        public string em_lea_cat { get; set; }
        public string em_clm_cat { get; set; }
        public string em_ins_cat { get; set; }
        public string em_status { get; set; }
        public Nullable<System.DateTime> em_pro_dat { get; set; }
        public string em_emp_typ { get; set; }
        public string em_sat_grp { get; set; }
        public Nullable<System.DateTime> em_sat_dat { get; set; }
        public string em_con_pri { get; set; }
        public string em_con_sec { get; set; }
        public string em_did { get; set; }
        public string em_thumb_id { get; set; }
        public string em_smtp_id { get; set; }
        public Nullable<short> em_acc_lvl { get; set; }
        public string em_usr_nam { get; set; }
        public string em_app_officer { get; set; }
        public string em_alt_officer { get; set; }
        public string em_remarks { get; set; }
        public string em_pay_slip { get; set; }
        public string em_mob_bill { get; set; }
        public string em_sta_ind { get; set; }
        public string em_sta_who { get; set; }
        public Nullable<System.DateTime> em_sta_dat { get; set; }
        public string em_grp_cod { get; set; }
        public string em_dept_cod { get; set; }
        public string em_design_cod { get; set; }
        public string em_child_nation { get; set; }
        public string em_blk_typ { get; set; }
        public string em_loc_cod { get; set; }
        public string em_mgmt_ent_cod { get; set; }
        public string em_letter_nam { get; set; }
        public string em_dept_grp_cod { get; set; }
    
        public virtual ss_emp_mas_add ss_emp_mas_add { get; set; }
    }
}
