//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_grp_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ss_emp_grp_mas()
        {
            this.ss_emp_grp_det = new HashSet<ss_emp_grp_det>();
        }
    
        public string gm_grp_cod { get; set; }
        public string gm_grp_desc { get; set; }
        public string gm_sta_ind { get; set; }
        public string gm_sta_who { get; set; }
        public Nullable<System.DateTime> gm_sta_dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_emp_grp_det> ss_emp_grp_det { get; set; }
    }
}
