//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_emp_grp_det
    {
        public string gd_grp_cod { get; set; }
        public int gd_itm_num { get; set; }
        public string gd_grp_day { get; set; }
        public string gd_wrk_ind { get; set; }
        public string gd_beg_tim { get; set; }
        public string gd_end_tim { get; set; }
        public string gd_hol_day { get; set; }
        public string gd_half_day { get; set; }
        public string gd_alt_day { get; set; }
        public string gd_ot_ind { get; set; }
        public string gd_ot_beg { get; set; }
        public string gd_ot_end { get; set; }
        public Nullable<double> gd_ot_hrs { get; set; }
        public string gd_half_DayA { get; set; }
    
        public virtual ss_emp_grp_mas ss_emp_grp_mas { get; set; }
    }
}
