//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_exp_lev
    {
        public int el_ref_num { get; set; }
        public System.DateTime el_beg_dat { get; set; }
        public System.DateTime el_end_dat { get; set; }
        public string el_sta_ind { get; set; }
        public string el_sta_who { get; set; }
        public System.DateTime el_sta_dat { get; set; }
    }
}
