//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_gentb_mails
    {
        public string gm_mail_num { get; set; }
        public string gm_mail_typ { get; set; }
        public string gm_mail_to { get; set; }
        public string gm_mail_cc { get; set; }
        public string gm_mail_subject { get; set; }
        public string gm_mail_body { get; set; }
        public string gm_mail_bodycc { get; set; }
        public string gm_sta_ind { get; set; }
        public string gm_sta_who { get; set; }
        public Nullable<System.DateTime> gm_sta_dat { get; set; }
    }
}
