//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_emp_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ss_lev_emp_mas()
        {
            this.ss_lev_emp_det = new HashSet<ss_lev_emp_det>();
            this.ss_lev_emp_det_his = new HashSet<ss_lev_emp_det_his>();
        }
    
        public string sm_ref_cod { get; set; }
        public string sm_emp_cod { get; set; }
        public string sm_lev_yr { get; set; }
        public string sm_sta_ind { get; set; }
        public string sm_sta_who { get; set; }
        public Nullable<System.DateTime> sm_sta_dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_lev_emp_det> ss_lev_emp_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_lev_emp_det_his> ss_lev_emp_det_his { get; set; }
    }
}
