//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_ent_mas
    {
        public string em_ent_cod { get; set; }
        public System.DateTime em_ent_dat { get; set; }
        public string em_cat_cod { get; set; }
        public string em_sta_ind { get; set; }
        public string em_sta_who { get; set; }
        public Nullable<System.DateTime> em_sta_dat { get; set; }
    }
}
