//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_typ
    {
        public string lt_lev_cod { get; set; }
        public string lt_lev_desc { get; set; }
        public string lt_shr_nam { get; set; }
        public string lt_cri_teria { get; set; }
        public string lt_sta_ind { get; set; }
        public string lt_sta_who { get; set; }
        public Nullable<System.DateTime> lt_sta_dat { get; set; }
        public string lt_yr_cod { get; set; }
        public Nullable<bool> lt_att_aws { get; set; }
    }
}
