//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_det_log
    {
        public string dl_bat_num { get; set; }
        public int dl_itm_num { get; set; }
        public System.DateTime dl_lev_dat { get; set; }
        public string dl_lev_cod { get; set; }
        public string dl_lev_urg { get; set; }
        public bool dl_lev_am { get; set; }
        public bool dl_lev_pm { get; set; }
        public string dl_rem_ark { get; set; }
        public string dl_req_to { get; set; }
        public string dl_app_by { get; set; }
        public string dl_app_ind { get; set; }
        public Nullable<System.DateTime> dl_app_dat { get; set; }
        public string dl_app_who { get; set; }
        public string dl_cov_by { get; set; }
        public string dl_app_remark { get; set; }
        public string dl_mc_ind { get; set; }
        public string dl_mc_num { get; set; }
        public string dl_sta_ind { get; set; }
        public string dl_sta_who { get; set; }
        public Nullable<System.DateTime> dl_sta_dat { get; set; }
        public Nullable<int> dl_mail_ind { get; set; }
        public string dl_edit_ind { get; set; }
        public string dl_exp_ind { get; set; }
    
        public virtual ss_lev_mas ss_lev_mas { get; set; }
    }
}
