//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_det
    {
        public string ld_bat_num { get; set; }
        public int ld_itm_num { get; set; }
        public System.DateTime ld_lev_dat { get; set; }
        public string ld_lev_cod { get; set; }
        public string ld_lev_urg { get; set; }
        public bool ld_lev_am { get; set; }
        public bool ld_lev_pm { get; set; }
        public string ld_rem_ark { get; set; }
        public string ld_req_to { get; set; }
        public string ld_app_by { get; set; }
        public string ld_app_ind { get; set; }
        public Nullable<System.DateTime> ld_app_dat { get; set; }
        public string ld_app_who { get; set; }
        public string ld_cov_by { get; set; }
        public string ld_app_remark { get; set; }
        public string ld_mc_ind { get; set; }
        public string ld_mc_num { get; set; }
        public string ld_sta_ind { get; set; }
        public string ld_sta_who { get; set; }
        public Nullable<System.DateTime> ld_sta_dat { get; set; }
        public Nullable<int> ld_mail_ind { get; set; }
        public string ld_edit_ind { get; set; }
        public string ld_exp_ind { get; set; }
    
        public virtual ss_lev_mas ss_lev_mas { get; set; }
    }
}
