//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_emp_det_his
    {
        public string dh_ref_cod { get; set; }
        public string dh_lev_cod { get; set; }
        public int dh_itm_num { get; set; }
        public System.DateTime dh_eff_dat { get; set; }
        public Nullable<decimal> dh_prev_lev_bf { get; set; }
        public Nullable<decimal> dh_prev_lev_ent { get; set; }
        public Nullable<decimal> dh_prev_cur_ent { get; set; }
        public Nullable<decimal> dh_prev_lev_add { get; set; }
        public Nullable<decimal> dh_lev_bf { get; set; }
        public Nullable<decimal> dh_lev_ent { get; set; }
        public Nullable<decimal> dh_cur_ent { get; set; }
        public Nullable<decimal> dh_lev_add { get; set; }
        public string dh_rem_ark { get; set; }
        public string dh_sta_ind { get; set; }
        public string dh_sta_who { get; set; }
        public Nullable<System.DateTime> dh_sta_dat { get; set; }
    
        public virtual ss_lev_emp_mas ss_lev_emp_mas { get; set; }
    }
}
