//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_lev_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ss_lev_mas()
        {
            this.ss_lev_det = new HashSet<ss_lev_det>();
            this.ss_lev_det_log = new HashSet<ss_lev_det_log>();
        }
    
        public string lm_bat_num { get; set; }
        public Nullable<System.DateTime> lm_bat_dat { get; set; }
        public string lm_emp_cod { get; set; }
        public string lm_sta_ind { get; set; }
        public string lm_sta_who { get; set; }
        public Nullable<System.DateTime> lm_sta_dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_lev_det> ss_lev_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ss_lev_det_log> ss_lev_det_log { get; set; }
    }
}
