//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_mail_cclist
    {
        public string ml_emp_cod { get; set; }
        public string ml_cat_cod { get; set; }
        public string ml_cc_emp { get; set; }
        public string ml_cc_rmk_emp { get; set; }
        public string ml_cc_dept { get; set; }
        public string ml_sta_ind { get; set; }
        public string ml_sta_who { get; set; }
        public Nullable<System.DateTime> ml_sta_dat { get; set; }
    }
}
