//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_ot_det
    {
        public string od_bat_num { get; set; }
        public int od_itm_num { get; set; }
        public System.DateTime od_ot_dat { get; set; }
        public string od_otf_tim { get; set; }
        public string od_ott_tim { get; set; }
        public string od_tot_hrs { get; set; }
        public decimal od_ot_meal { get; set; }
        public decimal od_ot_trans { get; set; }
        public bool od_ot_night { get; set; }
        public string od_rem_ark { get; set; }
        public string od_ver_by { get; set; }
        public Nullable<System.DateTime> od_ver_dat { get; set; }
        public string od_ver_remark { get; set; }
        public string od_app_by { get; set; }
        public string od_app_ind { get; set; }
        public Nullable<System.DateTime> od_app_dat { get; set; }
        public string od_app_who { get; set; }
        public string od_app_remark { get; set; }
        public string od_pay_ind { get; set; }
        public string od_pay_who { get; set; }
        public Nullable<System.DateTime> od_pay_dat { get; set; }
        public string od_ref_num { get; set; }
        public string od_sta_ind { get; set; }
        public string od_sta_who { get; set; }
        public Nullable<System.DateTime> od_sta_dat { get; set; }
        public string od_clm_ind { get; set; }
        public Nullable<System.DateTime> od_clm_dat { get; set; }
    
        public virtual ss_ot_mas ss_ot_mas { get; set; }
    }
}
