//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_par_ams
    {
        public int pa_par_num { get; set; }
        public string pa_par_typ { get; set; }
        public string pa_par_desc { get; set; }
        public string pa_str_val { get; set; }
        public Nullable<float> pa_num_val { get; set; }
        public Nullable<System.DateTime> pa_dat_val { get; set; }
        public string pa_sta_ind { get; set; }
        public string pa_sta_who { get; set; }
        public Nullable<System.DateTime> pa_sta_dat { get; set; }
    }
}
