//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_req_mas
    {
        public string rm_req_num { get; set; }
        public System.DateTime rm_req_dat { get; set; }
        public string rm_emp_cod { get; set; }
        public string rm_blk_no { get; set; }
        public string rm_str_nam { get; set; }
        public string rm_lvl_no { get; set; }
        public string rm_unit_no { get; set; }
        public string rm_build_nam { get; set; }
        public string rm_zip_cod { get; set; }
        public string rm_loc_home { get; set; }
        public string rm_loc_mob { get; set; }
        public string rm_loc_con { get; set; }
        public string rm_email { get; set; }
        public string rm_con_person { get; set; }
        public string rm_con_no { get; set; }
        public string rm_con_mail { get; set; }
        public string rm_con_relation { get; set; }
        public string rm_sta_ind { get; set; }
        public string rm_sta_who { get; set; }
        public Nullable<System.DateTime> rm_sta_dat { get; set; }
    }
}
