//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_rep_officer
    {
        public int ro_id { get; set; }
        public string ro_emp_type { get; set; }
        public string ro_emp_cod { get; set; }
        public string ro_repoff_type { get; set; }
        public string ro_repoff_cod { get; set; }
        public string ro_sta_ind { get; set; }
        public string ro_sta_who { get; set; }
        public Nullable<System.DateTime> ro_sta_dat { get; set; }
    }
}
