//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_sub_menus
    {
        public int sm_sub_id { get; set; }
        public int sm_mnu_id { get; set; }
        public string sm_mnu_des { get; set; }
        public string sm_mnu_val { get; set; }
        public Nullable<int> sm_mnu_ord { get; set; }
        public string sm_mnu_lnk { get; set; }
        public string sm_mnu_img { get; set; }
        public string sm_sta_ind { get; set; }
    
        public virtual ss_main_menus ss_main_menus { get; set; }
    }
}
