//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_sop_file_mas
    {
        public int fm_rec_num { get; set; }
        public string fm_dept_cod { get; set; }
        public Nullable<System.DateTime> fm_eff_dat { get; set; }
        public string fm_doc_nam { get; set; }
        public string fm_file_nam { get; set; }
        public string fm_file_desc { get; set; }
        public string fm_sta_ind { get; set; }
        public string fm_sta_who { get; set; }
        public Nullable<System.DateTime> fm_sta_dat { get; set; }
    
        public virtual ss_sop_dept_mas ss_sop_dept_mas { get; set; }
    }
}
