//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_swap_mas
    {
        public string ss_bat_num { get; set; }
        public System.DateTime ss_bat_dat { get; set; }
        public string ss_emp_cod { get; set; }
        public System.DateTime ss_swap_from { get; set; }
        public System.DateTime ss_swap_to { get; set; }
        public string ss_swap_typ { get; set; }
        public string ss_swap_with { get; set; }
        public string ss_rem_ark { get; set; }
        public string ss_app_ind { get; set; }
        public Nullable<System.DateTime> ss_acc_dat { get; set; }
        public string ss_acc_who { get; set; }
        public string ss_sta_ind { get; set; }
        public string ss_sta_who { get; set; }
        public Nullable<System.DateTime> ss_sta_dat { get; set; }
    }
}
