//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_usr_access
    {
        public string ua_emp_cod { get; set; }
        public string ua_main_mnu { get; set; }
        public string ua_sub_mnu { get; set; }
        public string ua_rpt_ind { get; set; }
        public string ua_rpt_dept { get; set; }
        public string ua_abs_ind { get; set; }
        public string ua_abs_dept { get; set; }
        public string ua_offday_ind { get; set; }
        public string ua_offday_dept { get; set; }
        public string ua_bdy_ind { get; set; }
        public string ua_bdy_dept { get; set; }
        public string ua_sta_ind { get; set; }
        public string ua_sta_who { get; set; }
        public Nullable<System.DateTime> ua_sta_dat { get; set; }
    }
}
