//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_ver_officer
    {
        public string vo_emp_cod { get; set; }
        public string vo_cat_cod { get; set; }
        public string vo_pri_cod { get; set; }
        public string vo_sec_cod { get; set; }
        public string vo_sta_ind { get; set; }
        public string vo_sta_who { get; set; }
        public Nullable<System.DateTime> vo_sta_dat { get; set; }
    }
}
