//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_vacant_mas
    {
        public int vm_id { get; set; }
        public string vm_emp_cod { get; set; }
        public string vm_emp_nam { get; set; }
        public string vm_sta_ind { get; set; }
        public string vm_sta_who { get; set; }
        public Nullable<System.DateTime> vm_sta_dat { get; set; }
        public string vm_dept_cod { get; set; }
        public string vm_loc_cod { get; set; }
        public string vm_dept_grp_cod { get; set; }
    }
}
