//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data.OrixEss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ss_yr_period
    {
        public string yp_ref_cod { get; set; }
        public string yp_yr_val { get; set; }
        public string yp_par_cod { get; set; }
        public System.DateTime yp_from_dat { get; set; }
        public System.DateTime yp_to_dat { get; set; }
        public string yp_sta_ind { get; set; }
        public string yp_sta_who { get; set; }
        public Nullable<System.DateTime> yp_sta_dat { get; set; }
    }
}
