//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfstb_asset_model_chd
    {
        public string cfs_chd_code { get; set; }
        public string cfs_chd_model_code { get; set; }
        public string cfs_chd_brand_code { get; set; }
        public string cfs_chd_model_sta_ind { get; set; }
        public string cfs_chd_model_sta_who { get; set; }
        public System.DateTime cfs_chd_model_sta_dat { get; set; }
    
        public virtual cfstb_asset_brand_mas cfstb_asset_brand_mas { get; set; }
        public virtual cfstb_asset_model_mas cfstb_asset_model_mas { get; set; }
    }
}
