//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_alert_mas
    {
        public string am_client_cod { get; set; }
        public string am_unit_cod { get; set; }
        public string am_alert_cat { get; set; }
        public string am_alert_rsn { get; set; }
        public System.DateTime am_eff_dat { get; set; }
        public string am_rem_ark { get; set; }
        public string am_sta_ind { get; set; }
        public string am_sta_who { get; set; }
        public System.DateTime am_sta_dat { get; set; }
    
        public virtual crmtb_client_mas crmtb_client_mas { get; set; }
    }
}
