//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_alert_bu_matrix
    {
        public string bm_unit_cod { get; set; }
        public string bm_trans_cod { get; set; }
        public string bm_sta_ind { get; set; }
        public string bm_sta_who { get; set; }
        public System.DateTime bm_sta_dat { get; set; }
    }
}
