//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_contact_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crmtb_client_contact_mas()
        {
            this.crmtb_client_contact_purpose = new HashSet<crmtb_client_contact_purpose>();
            this.crmtb_client_contact_det = new HashSet<crmtb_client_contact_det>();
        }
    
        public string cm_con_cod { get; set; }
        public string cm_ref_typ { get; set; }
        public string cm_ref_cod { get; set; }
        public string cm_con_typ { get; set; }
        public string cm_title { get; set; }
        public string cm_full_nam { get; set; }
        public string cm_sur_nam { get; set; }
        public string cm_first_nam { get; set; }
        public string cm_con_gender { get; set; }
        public string cm_con_nric { get; set; }
        public string cm_con_design { get; set; }
        public string cm_grp_cod { get; set; }
        public string cm_created_by { get; set; }
        public System.DateTime cm_created_dat { get; set; }
        public string cm_sta_ind { get; set; }
        public string cm_sta_who { get; set; }
        public System.DateTime cm_sta_dat { get; set; }
    
        public virtual crmtb_client_dept crmtb_client_dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmtb_client_contact_purpose> crmtb_client_contact_purpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmtb_client_contact_det> crmtb_client_contact_det { get; set; }
    }
}
