//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_para_meter
    {
        public string pm_par_cod { get; set; }
        public string pm_grp_cod { get; set; }
        public string pm_sub_cod { get; set; }
        public string pm_par_desc { get; set; }
        public string pm_sht_desc { get; set; }
        public Nullable<int> pm_ord_ind { get; set; }
        public string pm_add_info { get; set; }
        public string pm_add_desc { get; set; }
        public string pm_created_by { get; set; }
        public System.DateTime pm_created_dat { get; set; }
        public string pm_sta_ind { get; set; }
        public string pm_sta_who { get; set; }
        public System.DateTime pm_sta_dat { get; set; }
    }
}
