//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_contact_det
    {
        public string cd_con_cod { get; set; }
        public int cd_itm_num { get; set; }
        public string cd_typ_cod { get; set; }
        public string cd_country_cod { get; set; }
        public string cd_area_cod { get; set; }
        public string cd_typ_val { get; set; }
        public string cd_created_by { get; set; }
        public System.DateTime cd_created_dat { get; set; }
        public string cd_sta_ind { get; set; }
        public string cd_sta_who { get; set; }
        public System.DateTime cd_sta_dat { get; set; }
    
        public virtual crmtb_client_contact_mas crmtb_client_contact_mas { get; set; }
    }
}
