//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_dept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crmtb_client_dept()
        {
            this.crmtb_client_contact_mas = new HashSet<crmtb_client_contact_mas>();
        }
    
        public string cd_ref_num { get; set; }
        public string cd_add_cod { get; set; }
        public string cd_dept_cod { get; set; }
        public string cd_grp_cod { get; set; }
        public string cd_dept_desc { get; set; }
        public string cd_einv_ind { get; set; }
        public string cd_created_by { get; set; }
        public System.DateTime cd_created_dat { get; set; }
        public string cd_sta_ind { get; set; }
        public string cd_sta_who { get; set; }
        public System.DateTime cd_sta_dat { get; set; }
    
        public virtual crmtb_client_address_mas crmtb_client_address_mas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmtb_client_contact_mas> crmtb_client_contact_mas { get; set; }
    }
}
