//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_id_mas
    {
        public string im_client_cod { get; set; }
        public string im_id_typ { get; set; }
        public string im_id_num { get; set; }
        public string im_created_by { get; set; }
        public System.DateTime im_created_dat { get; set; }
        public string im_sta_ind { get; set; }
        public string im_sta_who { get; set; }
        public System.DateTime im_sta_dat { get; set; }
    
        public virtual crmtb_client_mas crmtb_client_mas { get; set; }
    }
}
