//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_address_mas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crmtb_client_address_mas()
        {
            this.crmtb_client_dept = new HashSet<crmtb_client_dept>();
        }
    
        public string am_add_cod { get; set; }
        public string am_ref_typ { get; set; }
        public string am_ref_cod { get; set; }
        public string am_blk_typ { get; set; }
        public string am_blk_num { get; set; }
        public string am_floor_num { get; set; }
        public string am_unit_num { get; set; }
        public string am_street_nam { get; set; }
        public string am_build_nam { get; set; }
        public string am_postal_cod { get; set; }
        public string am_country_cod { get; set; }
        public string am_area_cod { get; set; }
        public string am_add_ind { get; set; }
        public string am_bill_ind { get; set; }
        public string am_created_by { get; set; }
        public System.DateTime am_created_dat { get; set; }
        public string am_sta_ind { get; set; }
        public string am_sta_who { get; set; }
        public System.DateTime am_sta_dat { get; set; }
    
        public virtual crmtb_client_mas crmtb_client_mas { get; set; }
        public virtual gentb_country_mas gentb_country_mas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmtb_client_dept> crmtb_client_dept { get; set; }
    }
}
