//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_contact_purpose
    {
        public string cp_con_cod { get; set; }
        public string cp_con_purpose_cod { get; set; }
        public string cp_remark { get; set; }
        public string cp_created_by { get; set; }
        public System.DateTime cp_created_dat { get; set; }
        public string cp_sta_ind { get; set; }
        public string cp_sta_who { get; set; }
        public System.DateTime cp_sta_dat { get; set; }
    
        public virtual crmtb_client_contact_mas crmtb_client_contact_mas { get; set; }
    }
}
