//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmtb_client_alert_waive_mas
    {
        public int wm_rec_num { get; set; }
        public string wm_client_cod { get; set; }
        public string wm_unit_cod { get; set; }
        public int wm_itm_num { get; set; }
        public System.DateTime wm_waive_frm { get; set; }
        public System.DateTime wm_waive_to { get; set; }
        public string wm_waive_ind { get; set; }
        public string wm_sta_ind { get; set; }
        public string wm_sta_who { get; set; }
        public System.DateTime wm_sta_dat { get; set; }
    }
}
