//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gentb_gen_gd
    {
        public string gd_grp_cod { get; set; }
        public string gd_gen_cod { get; set; }
        public string gd_gen_des { get; set; }
        public string gd_att_cd1 { get; set; }
        public string gd_att_cd2 { get; set; }
        public string gd_ind_001 { get; set; }
        public string gd_ind_002 { get; set; }
        public string gd_att_cd3 { get; set; }
        public Nullable<System.DateTime> gd_date { get; set; }
        public decimal recordno { get; set; }
    }
}
