//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gentb_car_mas
    {
        public string cm_car_cod { get; set; }
        public string cm_car_mak { get; set; }
        public string cm_car_mod { get; set; }
        public string cm_car_cap { get; set; }
        public string cm_car_cls { get; set; }
        public string cm_car_typ_old { get; set; }
        public string cm_act_cap { get; set; }
        public string cm_sta_who { get; set; }
        public Nullable<System.DateTime> cm_sta_dat { get; set; }
        public string cm_sta_ind { get; set; }
        public string cm_mod_cod { get; set; }
        public string cm_fac_lif { get; set; }
        public string cm_pkg_age { get; set; }
        public string cm_dor_typ { get; set; }
        public Nullable<int> cm_sea_ter { get; set; }
        public string cm_tur_bo { get; set; }
        public string cm_whl_bed { get; set; }
        public string cm_mat_erial { get; set; }
        public string cm_car_fuel { get; set; }
        public string cm_pla_te { get; set; }
        public string cm_tra_mission { get; set; }
        public string cm_car_typ { get; set; }
        public string cm_opr_ind { get; set; }
        public string cm_veh_typ { get; set; }
        public Nullable<double> cm_laden_weigh { get; set; }
        public Nullable<double> cm_axles { get; set; }
        public Nullable<int> cm_len_gth { get; set; }
        public string cm_ext_ion { get; set; }
        public Nullable<double> cm_ton_age { get; set; }
        public Nullable<System.DateTime> cm_eff_frm { get; set; }
    }
}
