//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_mas
    {
        public string em_emp_cod { get; set; }
        public string em_emp_nam { get; set; }
        public string em_alias { get; set; }
        public System.DateTime em_birth_dat { get; set; }
        public string em_sex { get; set; }
        public string em_nation { get; set; }
        public string em_race { get; set; }
        public string em_mar_sta { get; set; }
        public string em_nric_pp { get; set; }
        public string em_inc_tax { get; set; }
        public string em_wrk_per { get; set; }
        public string em_home_pho { get; set; }
        public string em_oth_con { get; set; }
        public string em_loc_add { get; set; }
        public string em_zip_cod { get; set; }
        public string em_oth_add { get; set; }
        public string em_spo_nam { get; set; }
        public string em_spo_pho { get; set; }
        public string em_job_des { get; set; }
        public string em_subsidiary { get; set; }
        public string em_dept { get; set; }
        public string em_emp_sta { get; set; }
        public System.DateTime em_joi_dat { get; set; }
        public Nullable<System.DateTime> em_cfm_dat { get; set; }
        public Nullable<System.DateTime> em_rsg_dat { get; set; }
        public string em_con_ind { get; set; }
        public string em_sat_grp { get; set; }
        public Nullable<System.DateTime> em_pro_dat { get; set; }
        public string em_sta_ind { get; set; }
        public System.DateTime em_sta_dat { get; set; }
        public string em_sta_who { get; set; }
        public string em_emp_typ { get; set; }
        public string em_div { get; set; }
        public string em_cpf { get; set; }
        public string em_con_tri { get; set; }
        public string em_pr_sts { get; set; }
        public string em_pr_dat { get; set; }
        public Nullable<decimal> em_contri_amt { get; set; }
        public string em_nt_id { get; set; }
        public string em_sybase_id { get; set; }
        public string em_exchg_id { get; set; }
        public string em_smtp_id { get; set; }
        public string em_exchg_gid { get; set; }
        public string em_smtp_gid { get; set; }
        public string em_lea_cat { get; set; }
        public string em_emp_flg { get; set; }
        public Nullable<System.DateTime> em_sat_date { get; set; }
        public Nullable<int> em_acc_lvl { get; set; }
        public string em_app_officer { get; set; }
        public string em_alt_officer { get; set; }
        public string em_sht_name { get; set; }
        public string em_oth_approval { get; set; }
        public string em_ot_category { get; set; }
        public string em_did { get; set; }
        public string em_job_alt { get; set; }
        public Nullable<System.DateTime> em_dob_child { get; set; }
        public string em_staff_status { get; set; }
        public string em_thumb_id { get; set; }
    }
}
