//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthozCapital.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrixDBEntities : DbContext
    {
        public OrixDBEntities()
            : base("name=OrixDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cfstb_asset_brand_mas> cfstb_asset_brand_mas { get; set; }
        public virtual DbSet<cfstb_asset_model_chd> cfstb_asset_model_chd { get; set; }
        public virtual DbSet<cfstb_asset_model_mas> cfstb_asset_model_mas { get; set; }
        public virtual DbSet<crmtb_alert_bu_matrix> crmtb_alert_bu_matrix { get; set; }
        public virtual DbSet<crmtb_client_alert_mas> crmtb_client_alert_mas { get; set; }
        public virtual DbSet<crmtb_client_alert_waive_mas> crmtb_client_alert_waive_mas { get; set; }
        public virtual DbSet<crmtb_client_entity_profile> crmtb_client_entity_profile { get; set; }
        public virtual DbSet<crmtb_client_mas> crmtb_client_mas { get; set; }
        public virtual DbSet<crmtb_para_meter> crmtb_para_meter { get; set; }
        public virtual DbSet<gentb_car_mas> gentb_car_mas { get; set; }
        public virtual DbSet<gentb_gen_gd> gentb_gen_gd { get; set; }
        public virtual DbSet<crmtb_client_id_mas> crmtb_client_id_mas { get; set; }
        public virtual DbSet<crmtb_client_address_mas> crmtb_client_address_mas { get; set; }
        public virtual DbSet<gentb_country_mas> gentb_country_mas { get; set; }
        public virtual DbSet<crmtb_client_dept> crmtb_client_dept { get; set; }
        public virtual DbSet<crmtb_client_contact_mas> crmtb_client_contact_mas { get; set; }
        public virtual DbSet<crmtb_client_contact_purpose> crmtb_client_contact_purpose { get; set; }
        public virtual DbSet<hr_emp_mas> hr_emp_mas { get; set; }
        public virtual DbSet<crmtb_client_contact_det> crmtb_client_contact_det { get; set; }
    }
}
